server:
  port: 10082
  servlet:
    context-path: /goods
spring:
  profiles:
    active: database,base
# 打印sql信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml