server:
  port: 10084
  servlet:
    context-path: /users
spring:
  profiles:
    active: base,database
  application:
    name: users
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# 熔断器
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

# 打印sql信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml