server:
  port: 10081
  servlet:
    context-path: /files
spring:
  profiles:
    active: base
  application:
    name: files
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
sms:
  accessKeyId: ENC(vx93YUB+2dxYzKAj1F4xJN7s2ESrn/N4ZbpQ0qjDknn9geweItBK4i1JZkAZiE235nEubM+WLGsZhIwpBULigg==)
  accessKeySecret: ENC(4Jf54OTywiFo/jex/kimK6VkrWtFQfYw8GXiXQMH8+mhVg5bfRUGy/fdy89SSczmeBjY+lJUcADl0Wlih3iY1w==)
jasypt:
  encryptor:
    password: yqsl