server:
  port: 10081
  servlet:
    context-path: /files
spring:
  profiles:
    active: base
  application:
    name: files
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB