spring:
  datasource:
    db1:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://148.70.100.4:3306/yqsl?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    db2:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://148.70.100.4:3307/yqsl?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456